--------------------begain-------------------

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 100) >= this->size() (which is 19)
Aborted (core dumped)